### ISSUE TITLE
Docker compose can't init

### ISSUE THREAD

**Issue by davidXire** [ssenart/gazpar2mqtt#11]
Hello

I used your example of docker-compose, however the process seems not able to init the config files in his directory. 
Here below my docker-compose file

'''
services:
  gazpar2mqtt:
    image: ssenart/gazpar2mqtt:latest
    container_name: gazpar2mqtt
    restart: unless-stopped
    network_mode: bridge
#    user: "1000:1000"
    volumes:
      - ./data/config:/app/config
      - ./data/log:/app/log
    environment:
      - GRDF_USERNAME=xxx@gmail.com
      - GRDF_PASSWORD=xxxx
      - GRDF_SCAN_INTERVAL=480
      - GRDF_PCE_IDENTIFIER=xxxx
      - MQTT_BROKER=192.168.x.x
      - MQTT_USERNAME=xxxx
      - MQTT_PASSWORD=xxxx
      - MQTT_PORT=1883
'''

**Comment by ssenart** [comment]
Hello, yes, it does not manage to parse your secrets.yaml.

Does the volume ./data/config:/app/config has mounted correctly ?

Could you open your secrets.yaml file and review its content syntax:
- Be attentive where double quotes are set.
- Your end-of-line convention must be Unix (LF).

It should have the following format with your environment variable replaced:

```yaml
grdf.username: "${GRDF_USERNAME}"
grdf.password: "${GRDF_PASSWORD}"
grdf.pce_identifier: "${GRDF_PCE_IDENTIFIER}"

mqtt.broker: "${MQTT_BROKER}"
mqtt.port: "${MQTT_PORT}"
mqtt.username: "${MQTT_USERNAME}"
mqtt.password: "${MQTT_PASSWORD}"
```

If all is fine, perhaps the file it loads is not the file your see for any reason.

To be sure, connect into the running container and review the file secrets.yaml inside the running container.

Hope this helps.
